services:
  web:
    image: eldekyfin/webhttrack
    container_name: web-htrrack
    network_mode: bridge
    ports:
      - 8120:8080
    volumes:
      - /mnt/cyberserver/www/html/httrack:/root/websites
    restart: unless-stopped
