services:
  web:
    image: eldekyfin/webhttrack
    container_name: web-htrrack
    ports:
      - 8110:8080
    volumes:
      - httrack:/root/websites
    restart: unless-stopped
volumes:
  httrack:
    driver: local-persist
    driver_opts:
      mountpoint: /data/httrack
